"""initial_schema

Revision ID: 925cb1b031db
Revises: 
Create Date: 2026-09-25 14:04:07.798073

"""
from typing import Sequence, Union
import geoalchemy2
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '925cb1b031db'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('population_source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
   
    op.create_index(op.f('ix_areas_id'), 'areas', ['id'], unique=False)
    op.create_table('city_uis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('methodology_version', sa.String(), nullable=True),
    sa.Column('area_snapshot_json', sa.JSON(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_city_uis_id'), 'city_uis', ['id'], unique=False)
    op.create_table('indicator_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('direction', sa.Enum('positive', 'negative', name='indicatordirection'), nullable=False),
    sa.Column('benchmark_min', sa.Float(), nullable=False),
    sa.Column('benchmark_max', sa.Float(), nullable=False),
    sa.Column('benchmark_source', sa.String(), nullable=True),
    sa.Column('methodology_version', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_indicator_definitions_id'), 'indicator_definitions', ['id'], unique=False)
    op.create_table('ai_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('insight_type', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_insights_id'), 'ai_insights', ['id'], unique=False)
    op.create_table('area_uis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('methodology_version', sa.String(), nullable=True),
    sa.Column('snapshot_id', sa.String(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_area_uis_id'), 'area_uis', ['id'], unique=False)
    op.create_table('development_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('profile_json', sa.JSON(), nullable=False),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_development_profiles_id'), 'development_profiles', ['id'], unique=False)
    op.create_table('facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('osm_id', sa.String(), nullable=True),
    sa.Column('facility_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_index(op.f('ix_facilities_id'), 'facilities', ['id'], unique=False)
    op.create_table('indicator_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('raw_metric', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('benchmark_min_used', sa.Float(), nullable=True),
    sa.Column('benchmark_max_used', sa.Float(), nullable=True),
    sa.Column('direction_used', sa.String(), nullable=True),
    sa.Column('snapshot_id', sa.String(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicator_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indicator_scores_id'), 'indicator_scores', ['id'], unique=False)
    op.create_table('indicator_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('raw_value', sa.Float(), nullable=True),
    sa.Column('raw_metric', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('quality_flag', sa.String(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicator_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indicator_values_id'), 'indicator_values', ['id'], unique=False)
    op.create_table('priority_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('current_score', sa.Float(), nullable=True),
    sa.Column('target_score', sa.Float(), nullable=True),
    sa.Column('gap', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('population_impact', sa.Float(), nullable=True),
    sa.Column('contextual_factor', sa.Float(), nullable=True),
    sa.Column('priority', sa.Float(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicator_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_priority_scores_id'), 'priority_scores', ['id'], unique=False)
    op.create_table('simulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('intervention_type', sa.String(), nullable=True),
    sa.Column('input_json', sa.JSON(), nullable=True),
    sa.Column('assumption_json', sa.JSON(), nullable=True),
    sa.Column('output_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulations_id'), 'simulations', ['id'], unique=False)
    op.create_table('adaptive_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('rationale', sa.String(), nullable=True),
    sa.Column('methodology_version', sa.String(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicator_definitions.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['development_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adaptive_weights_id'), 'adaptive_weights', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adaptive_weights_id'), table_name='adaptive_weights')
    op.drop_table('adaptive_weights')
    op.drop_index(op.f('ix_simulations_id'), table_name='simulations')
    op.drop_table('simulations')
    op.drop_index(op.f('ix_priority_scores_id'), table_name='priority_scores')
    op.drop_table('priority_scores')
    op.drop_index(op.f('ix_indicator_values_id'), table_name='indicator_values')
    op.drop_table('indicator_values')
    op.drop_index(op.f('ix_indicator_scores_id'), table_name='indicator_scores')
    op.drop_table('indicator_scores')
    op.drop_index(op.f('ix_facilities_id'), table_name='facilities')
    op.drop_index('idx_facilities_geometry', table_name='facilities', postgresql_using='gist')
    op.drop_table('facilities')
    op.drop_index(op.f('ix_development_profiles_id'), table_name='development_profiles')
    op.drop_table('development_profiles')
    op.drop_index(op.f('ix_area_uis_id'), table_name='area_uis')
    op.drop_table('area_uis')
    op.drop_index(op.f('ix_ai_insights_id'), table_name='ai_insights')
    op.drop_table('ai_insights')
    op.drop_index(op.f('ix_indicator_definitions_id'), table_name='indicator_definitions')
    op.drop_table('indicator_definitions')
    op.drop_index(op.f('ix_city_uis_id'), table_name='city_uis')
    op.drop_table('city_uis')
    op.drop_index(op.f('ix_areas_id'), table_name='areas')
    op.drop_index('idx_areas_geometry', table_name='areas', postgresql_using='gist')
    op.drop_table('areas')
    # ### end Alembic commands ###
